### ISSUE TITLE
Why PixelOS images are RO?

### ISSUE THREAD

**Issue by muhammadbahaa2001** [MisterZtr/PixelOS_gsi#10]
Why PixelOS images are SO not RW? I know, to reduce it's size but, is not there any way to make it RW? I like to modify system freely.

**Comment by SowTag** [comment]
Images are RO due to a filesystem-level feature called Block Sharing. This can be disabled using `e2fsck` in UNIX-based systems. That is, Linux, MacOS and Windows on WSL.

To convert an image to RW:

`e2fsck -yf image.img`
`resize2fs image.img 7500M`
`e2fsck -yf -E unshare_blocks image.img`

And done. You should be able to `mount` the image.

If you mean live RW permissions as in the old days of Android when you could just edit files from your /system partition, I'd strongly discourage doing so. I don't think it's even possible in modern Android versions.

If you want to edit files do so systemlessly using Magisk or KernelSU.
